### PR TITLE
[ExtensionsMetadataGenerator] fixing infinite recursion bug; logging improvements

### LINKED ISSUE #4055: dotnet publish fails with 'Metadata generation failed' sometimes
#### Repro steps

Provide the steps required to reproduce the problem:

dotnet publish C:\temp\OurFunctionApp.csproj -c Release -o C:\temp\output

#### Expected behavior

It should build without an error.

#### Actual behavior

```
OurFunctionApp -> C:\temp\bin\Release\netcoreapp2.1\bin\OurFunctionApp.dll
C:\Users\build-admin\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(20,5): error : Metadata generation failed. [C:\temp\OurFunctionApp.csproj]
```

Output of dotnet --version: 2.1.503

This error occurs sporadically on our Jenkins server. I can't reproduce it on my computer. Also, I cannot reproduce it if run this command on the Jenkins server from command line prompt.

Can you help?

### PR DESCRIPTION
**Pull request by brettsam**
Fixes #4055.

With the help of several customers, I found one scenario where we hit infinite recursion and end up with a StackOverflowException. I was able to repro this by creating an empty AspNetCore MVC app in my solution and publishing it with something like `dotnet publish ..\FunctionApp55.sln -o e:\publish`. This put the Web app assembly in the Function bin directory, which means we'd scan it. 

The culprit seems to be a dependency on `Microsoft.AspNetCore.Razor.Runtime`, which does not get deployed along with the Web application. When we can't find it, we attempt an `Assembly.Load(<assembly name without version>)` to hopefully find it already loaded (this works with some core assemblies that have version mismatches but are still load-able). In this case, that initiates a recursion where we keep trying to load that assembly forever. 

Now, if I see that a load request was initiated by the generator assembly itself, I abort the load and log a message that this assembly cannot be scanned for extensions (which I'm assuming 99+% of the time is perfectly fine).

I've also added a *ton* more logging here. This should help us diagnose issues in the future. In the normal build process you won't see it, but if you either hit a process crash or enable detailed+ msbuild verbosity, they'll show up and will make debugging things like this a ton easier.

As an example, here's some relevant details in my build output when I run against my repro:

`dotnet publish ..\FunctionApp55.sln -o e:\publish -v:d`

```
         Found 58 assemblies to evaluate in 'e:\publish\bin':
           FunctionApp55.dll
             Resolving assembly: 'Microsoft.Azure.WebJobs.Host, Version=3.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
             Assembly 'Microsoft.Azure.WebJobs.Host' loaded from 'e:\publish\bin\Microsoft.Azure.WebJobs.Host.dll'.
             Found extension: MyFunctionApp55.Startup, FunctionApp55, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
           Microsoft.ApplicationInsights.dll
           Microsoft.AspNetCore.Authentication.Abstractions.dll

           ...snip...

           Microsoft.Azure.WebJobs.Extensions.CosmosDB.dll
             Found extension: Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
           Microsoft.Azure.WebJobs.Host.dll

           ..snip..

           Newtonsoft.Json.dll
           WebApplication18.dll
             Resolving assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
             Assembly 'Microsoft.AspNetCore.Mvc.Core' loaded from 'e:\publish\bin\Microsoft.AspNetCore.Mvc.Core.dll'.
             Resolving assembly: 'Microsoft.AspNetCore.Razor.Runtime, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
             Resolving assembly: 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'
             Cannot load 'Microsoft.AspNetCore.Razor.Runtime'. Aborting assembly resolution.
             Unable to find fallback for assembly 'Microsoft.AspNetCore.Razor.Runtime'. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
         File name: 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'
            at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
            at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
            at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
            at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
            at System.Reflection.Assembly.Load(String assemblyString)
            at ExtensionsMetadataGenerator.Console.Program.AssemblyLoader.<>c__DisplayClass1_0.<Initialize>b__0(Object sender, ResolveEventArgs args) in C:\git\functions_v2\azure-functions-host\tools\ExtensionsMetadataGenerator\src\ExtensionsMetadataGenerator.Console\Program.cs:line 78

           WebApplication18.Views.dll
             Resolving assembly: 'Microsoft.AspNetCore.Razor.Runtime, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
             Resolving assembly: 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'
             Cannot load 'Microsoft.AspNetCore.Razor.Runtime'. Aborting assembly resolution.
             Unable to find fallback for assembly 'Microsoft.AspNetCore.Razor.Runtime'. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
         File name: 'Microsoft.AspNetCore.Razor.Runtime, Culture=neutral, PublicKeyToken=null'
            at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
            at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
            at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
            at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
            at System.Reflection.Assembly.Load(String assemblyString)
            at ExtensionsMetadataGenerator.Console.Program.AssemblyLoader.<>c__DisplayClass1_0.<Initialize>b__0(Object sender, ResolveEventArgs args) in C:\git\functions_v2\azure-functions-host\tools\ExtensionsMetadataGenerator\src\ExtensionsMetadataGenerator.Console\Program.cs:line 78

         'e:\publish\bin\extensions.json' successfully written.
```

### CODE REVIEW

File: tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExtensionsMetadataGeneratorTests.cs [hunk 1]
```diff
@@ -27,21 +27,37 @@ public void Generator_DifferentTargetFrameworks()
...
+                Assert.Single(extensions, e => e["name"].ToString() == "BarExtension" && e["typeName"].ToString().StartsWith("ExtensionsMetadataGeneratorTests.BarWebJobsStartup, ExtensionsMetadataGeneratorTests"));
+                Assert.Single(extensions, e => e["name"].ToString() == "Startup" && e["typeName"].ToString().StartsWith("TestProject_Core21.Startup"));
+                Assert.Single(extensions, e => e["name"].ToString() == "Startup" && e["typeName"].ToString().StartsWith("TestProject_Core22.Startup"));
+
+                // We cannot read TestProject_Razor.dll because it has a dependency we cannot find. Make sure
+                // we log correctly even though we've skipped this assembly.
+                Assert.Contains("Cannot load 'Microsoft.AspNetCore.Razor.Runtime'. Aborting assembly resolution.", log.ToString());
+                Assert.Contains("Could not evaluate 'TestProject_Razor.dll' for extension metadata. If this assembly contains a Functions extension, ensure that all dependent assemblies exist in ", log.ToString());
```
Comment (brettsam) [inline tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExtensionsMetadataGeneratorTests.cs]: Once I added the Razor project, this test ran into the same StackOverflowException that customers were reporting. Now I make sure that we succeed and log the problem correctly.

File: tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionsMetadataGenerator.cs [hunk 2]
```diff
@@ -52,9 +52,16 @@ public static void Generate(string sourcePath, string outputPath, ConsoleLogger
...
                         {
-                            logger.LogError($"Could not evaluate '{Path.GetFileName(path)}' for extension metadata. If this assembly contains a Functions extension, ensure that all dependent assemblies exist in '{sourcePath}'. If this assembly does not contain any Functions extensions, this message can be ignored. Exception message: {exc.Message}");
+                            // Don't log this as an error. This will almost always happen due to some publishing artifacts (i.e. Razor) existing
+                            // in the functions bin folder without all of their dependencies present. These will almost never have Functions extensions,
+                            // so we don't want to write out errors every time there is a build. This message can be seen with detailed logging enabled.
+                            logger.LogMessage($"Could not evaluate '{Path.GetFileName(path)}' for extension metadata. If this assembly contains a Functions extension, ensure that all dependent assemblies exist in '{sourcePath}'. If this assembly does not contain any Functions extensions, this message can be ignored. Exception message: {ex.Message}");
```
Comment (brettsam) [inline tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionsMetadataGenerator.cs]: I decided to make this a message b/c it's almost never going to be an issue so it felt wrong to constantly log warnings to people that had builds set up this way. This allows it to be discoverable (by turning on detailed msbuild logging) yet not constantly warning.

**Comment by brettsam** [comment]
@soninaren / @fabiocav -- can I get a review on this? I think it'll solve a bunch of people's problems with metadata generation.
